name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Create GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.RUBRION_APP_ID }}
          private-key: ${{ secrets.RUBRION_APP_SECRET }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          apiToken: ${{ secrets.CF_API_TOKEN }}
          projectName: ${{ vars.PROJECT_NAME }}
          directory: dist
          branch: ${{ github.ref_name }}

      - name: Configure Custom Domain for Production
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X PATCH "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CF_ACCOUNT_ID }}/pages/projects/${{ vars.PROJECT_NAME }}" \
          -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{
            "custom_domain": "${{ vars.PROJECT_NAME }}.rubrion.com"
          }'

      - name: Configure Custom Domain for Release Branch
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          VERSION_SLUG=$(echo "${{ github.ref_name }}" | sed 's/release\///' | tr '/' '-')
          curl -X PATCH "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CF_ACCOUNT_ID }}/pages/projects/${{ vars.PROJECT_NAME }}" \
          -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{
            "custom_domain": "'"$VERSION_SLUG.${{ vars.PROJECT_NAME }}.rubrion.com"'"
          }'
