name: Release Versioning

on:
  push:
    branches:
      - develop

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Generate version and changelog
        id: version
        run: |
          npx standard-version --dry-run
          VERSION=$(npx standard-version --first-release --dry-run | grep -oP 'v\K[0-9]+\.[0-9]+\.[0-9]+')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Generated version: $VERSION"

      - name: Push to release branch
        env:
          TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          RELEASE_BRANCH="release/v$VERSION"

          npx standard-version

          git checkout -b $RELEASE_BRANCH || git checkout $RELEASE_BRANCH
          git push https://x-access-token:${TOKEN}@github.com/rubenszinho/gazillion-beers.git $RELEASE_BRANCH
