name: Release Versioning

on:
  push:
    branches:
      - develop

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.VERSION_BUMPER_APPID }}
          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Generate version and changelog
        id: version
        run: |
          VERSION=$(npx standard-version --dry-run | grep -oP 'v\K[0-9]+\.[0-9]+\.[0-9]+')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Generated version: $VERSION"

      - name: Push to release branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          RELEASE_BRANCH="release/v$VERSION"

          npx standard-version

          git checkout -b $RELEASE_BRANCH || git checkout $RELEASE_BRANCH
          git push origin HEAD --follow-tags
